# OpenAI Gym and Q-learning

In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [4]:
env = gym.make('FrozenLake-v1')

In [5]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [7]:
rewards_all_episosodes = []

# Q-learning algorithm
for episode in range(num_episodes):  # in each episode
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):  # in each time stamp
        
        # Exploration-exploitation trade-off
        exploration_rate_treshold = random.uniform(0, 1)
        if exploration_rate_treshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table for Q(s, a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break

    
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    rewards_all_episosodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episosodes), num_episodes/1000)
count = 1000
print("**********Average reward per thousand episodes***********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

# Print updated Q-table
print("\n\n**********Q-table**********\n")
print(q_table)

**********Average reward per thousand episodes***********

1000 :  0.047000000000000035
2000 :  0.22600000000000017
3000 :  0.4200000000000003
4000 :  0.5550000000000004
5000 :  0.6080000000000004
6000 :  0.6780000000000005
7000 :  0.6950000000000005
8000 :  0.6670000000000005
9000 :  0.6740000000000005
10000 :  0.6820000000000005


**********Q-table**********

[[0.4344816  0.43261296 0.43410479 0.43248281]
 [0.35462069 0.29671643 0.29431139 0.41933677]
 [0.398638   0.40570311 0.40638497 0.41048927]
 [0.24426195 0.36559701 0.37786302 0.40574836]
 [0.44021848 0.36594376 0.37623774 0.34271029]
 [0.         0.         0.         0.        ]
 [0.16636297 0.17001861 0.31201624 0.14387726]
 [0.         0.         0.         0.        ]
 [0.33377266 0.39097127 0.44719743 0.45468808]
 [0.42113558 0.47525641 0.36579386 0.42391461]
 [0.34532765 0.31599878 0.32394215 0.32174073]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.3984143  0.36764405 0

# Watch Q-learning agent play game

In [8]:
for episode in range(10):
    state = env.reset()
    done = False
    print(f"EPISODE {episode+1}\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("YOU WIN")
                time.sleep(3)
            else:
                print("YOU FELL")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state

env.close()

KeyboardInterrupt: 